# datasource
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/onebook_java?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone = GMT
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

---
# sqlite
#spring:
#  datasource:
#    driver-class-name: org.sqlite.JDBC
#    url: jdbc:sqlite:onebook.db

---
# mybatis
mybatis:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

---
spring:
  thymeleaf:
    cache: false